[general]
import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

[font.normal]
family = "JetBrains Mono Nerd Font"
style= "Regular"

[font]
size = 14.5

[window]
padding = { x = 7, y = 7 }
opacity = 0.90
